export interface modeInfoSingle{
    name: string;
    mode: string;
}

export enum EditorType{
    CODE = "A",
    MARKDOWN = "B",
    SPREADSHEET = "C",
}

export function typeEnumToString(typeEnum: number){
    const typeEnumToStringList = ["Code", "Text", "Spreadsheet"];
    return typeEnumToStringList[typeEnum];
}

export const modeInfo: Record<string, modeInfoSingle> = {
    "AB":{name:"APL",mode: "apl"},
    "AC":{name:"PGP",mode: "asciiarmor"},
    "AD":{name:"ASN.1",mode: "asn.1"},
    "AE":{name:"Asterisk",mode: "asterisk"},
    "AF":{name:"Brainfuck",mode: "brainfuck"},
    "AG":{name:"C",mode: "clike"},
    "AH":{name:"C++",mode: "clike"},
    "AI":{name:"Cobol",mode: "cobol"},
    "AJ":{name:"C#",mode: "clike"},
    "AK":{name:"Clojure",mode: "clojure"},
    "AL":{name:"ClojureScript",mode: "clojure"},
    "AM":{name:"Closure Stylesheets (GSS)",mode: "css"},
    "AN":{name:"CMake",mode: "cmake"},
    "AO":{name:"CoffeeScript",mode: "coffeescript"},
    "AP":{name:"Common Lisp",mode: "commonlisp"},
    "AQ":{name:"Cypher",mode: "cypher"},
    "AR":{name:"Cython",mode: "python"},
    "AS":{name:"Crystal",mode: "crystal"},
    "AT":{name:"CSS",mode: "css"},
    "AU":{name:"CQL",mode: "sql"},
    "AV":{name:"D",mode: "d"},
    "AW":{name:"Dart",mode: "dart"},
    "AX":{name:"diff",mode: "diff"},
    "AY":{name:"Django",mode: "django"},
    "AZ":{name:"Dockerfile",mode: "dockerfile"},
    "Aa":{name:"DTD",mode: "dtd"},
    "Ab":{name:"Dylan",mode: "dylan"},
    "Ac":{name:"EBNF",mode: "ebnf"},
    "Ad":{name:"ECL",mode: "ecl"},
    "Ae":{name:"edn",mode: "clojure"},
    "Af":{name:"Eiffel",mode: "eiffel"},
    "Ag":{name:"Elm",mode: "elm"},
    "Ah":{name:"Embedded JavaScript",mode: "htmlembedded"},
    "Ai":{name:"Embedded Ruby",mode: "htmlembedded"},
    "Aj":{name:"Erlang",mode: "erlang"},
    "Ak":{name:"Esper",mode: "sql"},
    "Al":{name:"Factor",mode: "factor"},
    "Am":{name:"FCL",mode: "fcl"},
    "An":{name:"Forth",mode: "forth"},
    "Ao":{name:"Fortran",mode: "fortran"},
    "Ap":{name:"F#",mode: "mllike"},
    "Aq":{name:"Gas",mode: "gas"},
    "Ar":{name:"Gherkin",mode: "gherkin"},
    "As":{name:"GitHub Flavored Markdown",mode: "gfm"},
    "At":{name:"Go",mode: "go"},
    "Au":{name:"Groovy",mode: "groovy"},
    "Av":{name:"HAML",mode: "haml"},
    "Aw":{name:"Haskell",mode: "haskell"},
    "Ax":{name:"Haskell (Literate)",mode: "haskell-literate"},
    "Ay":{name:"Haxe",mode: "haxe"},
    "Az":{name:"HXML",mode: "haxe"},
    "A0":{name:"ASP.NET",mode: "htmlembedded"},
    "A1":{name:"HTML",mode: "htmlmixed"},
    "A2":{name:"HTTP",mode: "http"},
    "A3":{name:"IDL",mode: "idl"},
    "A4":{name:"Pug",mode: "pug"},
    "A5":{name:"Java",mode: "clike"},
    "A6":{name:"Java Server Pages",mode: "htmlembedded"},
    "A7":{name:"JavaScript",mode: "javascript"},
    "A8":{name:"JSON",mode: "javascript"},
    "A9":{name:"JSON-LD",mode: "javascript"},
    "A+":{name:"JSX",mode: "jsx"},
    "A/":{name:"Jinja2",mode: "jinja2"},
    "BA":{name:"Julia",mode: "julia"},
    "BB":{name:"Kotlin",mode: "clike"},
    "BC":{name:"LESS",mode: "css"},
    "BD":{name:"LiveScript",mode: "livescript"},
    "BE":{name:"Lua",mode: "lua"},
    "BG":{name:"mIRC",mode: "mirc"},
    "BH":{name:"MariaDB SQL",mode: "sql"},
    "BI":{name:"Mathematica",mode: "mathematica"},
    "BJ":{name:"Modelica",mode: "modelica"},
    "BK":{name:"MUMPS",mode: "mumps"},
    "BL":{name:"MS SQL",mode: "sql"},
    "BM":{name:"mbox",mode: "mbox"},
    "BN":{name:"MySQL",mode: "sql"},
    "BO":{name:"Nginx",mode: "nginx"},
    "BP":{name:"NSIS",mode: "nsis"},
    "BQ":{name:"NTriples",mode: "ntriples"},
    "BR":{name:"Objective-C",mode: "clike"},
    "BS":{name:"Objective-C++",mode: "clike"},
    "BT":{name:"OCaml",mode: "mllike"},
    "BU":{name:"Octave",mode: "octave"},
    "BV":{name:"Oz",mode: "oz"},
    "BW":{name:"Pascal",mode: "pascal"},
    "BX":{name:"PEG.js",mode: "pegjs"},
    "BY":{name:"Perl",mode: "perl"},
    "BZ":{name:"PHP",mode: "php"},
    "Ba":{name:"Pig",mode: "pig"},
    "Bb":{name:"Plain Text",mode: "null"},
    "Bc":{name:"PLSQL",mode: "sql"},
    "Bd":{name:"PostgreSQL",mode: "sql"},
    "Be":{name:"PowerShell",mode: "powershell"},
    "Bf":{name:"Properties files",mode: "properties"},
    "Bg":{name:"ProtoBuf",mode: "protobuf"},
    "Bh":{name:"Python",mode: "python"},
    "Bi":{name:"Puppet",mode: "puppet"},
    "Bj":{name:"Q",mode: "q"},
    "Bk":{name:"R",mode: "r"},
    "Bl":{name:"reStructuredText",mode: "rst"},
    "Bm":{name:"RPM Changes",mode: "rpm"},
    "Bn":{name:"RPM Spec",mode: "rpm"},
    "Bo":{name:"Ruby",mode: "ruby"},
    "Bp":{name:"Rust",mode: "rust"},
    "Bq":{name:"SAS",mode: "sas"},
    "Br":{name:"Sass",mode: "sass"},
    "Bs":{name:"Scala",mode: "clike"},
    "Bt":{name:"Scheme",mode: "scheme"},
    "Bu":{name:"SCSS",mode: "css"},
    "Bv":{name:"Shell",mode: "shell"},
    "Bw":{name:"Sieve",mode: "sieve"},
    "Bx":{name:"Slim",mode: "slim"},
    "By":{name:"Smalltalk",mode: "smalltalk"},
    "Bz":{name:"Smarty",mode: "smarty"},
    "B0":{name:"Solr",mode: "solr"},
    "B1":{name:"SML",mode: "mllike"},
    "B2":{name:"Soy",mode: "soy"},
    "B3":{name:"SPARQL",mode: "sparql"},
    "B4":{name:"Spreadsheet",mode: "spreadsheet"},
    "B5":{name:"SQL",mode: "sql"},
    "B6":{name:"SQLite",mode: "sql"},
    "B7":{name:"Squirrel",mode: "clike"},
    "B8":{name:"Stylus",mode: "stylus"},
    "B9":{name:"Swift",mode: "swift"},
    "B+":{name:"sTeX",mode: "stex"},
    "B/":{name:"LaTeX",mode: "stex"},
    "CA":{name:"SystemVerilog",mode: "verilog"},
    "CB":{name:"Tcl",mode: "tcl"},
    "CC":{name:"Textile",mode: "textile"},
    "CD":{name:"TiddlyWiki",mode: "tiddlywiki"},
    "CE":{name:"Tiki wiki",mode: "tiki"},
    "CF":{name:"TOML",mode: "toml"},
    "CG":{name:"Tornado",mode: "tornado"},
    "CH":{name:"troff",mode: "troff"},
    "CI":{name:"TTCN",mode: "ttcn"},
    "CJ":{name:"TTCN_CFG",mode: "ttcn-cfg"},
    "CK":{name:"Turtle",mode: "turtle"},
    "CL":{name:"TypeScript",mode: "javascript"},
    "CM":{name:"TypeScript-JSX",mode: "jsx"},
    "CN":{name:"Twig",mode: "twig"},
    "CO":{name:"Web IDL",mode: "webidl"},
    "CP":{name:"VB.NET",mode: "vb"},
    "CQ":{name:"VBScript",mode: "vbscript"},
    "CR":{name:"Velocity",mode: "velocity"},
    "CS":{name:"Verilog",mode: "verilog"},
    "CT":{name:"VHDL",mode: "vhdl"},
    "CU":{name:"Vue.js Component",mode: "vue"},
    "CV":{name:"XML",mode: "xml"},
    "CW":{name:"XQuery",mode: "xquery"},
    "CX":{name:"Yacas",mode: "yacas"},
    "CY":{name:"YAML",mode: "yaml"},
    "CZ":{name:"Z80",mode: "z80"},
    "Ca":{name:"mscgen",mode: "mscgen"},
    "Cb":{name:"xu",mode: "mscgen"},
    "Cc":{name:"msgenny",mode: "mscgen"},
    "Cd":{name:"WebAssembly",mode: "wast"},
    "Ce":{name:"Markdown",mode: "markdown"},
    // "Cf":{name:"Spreadsheet",mode: "spreadsheet"},
};

export const typeInfo: { [key in EditorType]: {name: string}} = {
    "A": {name: "Code"},
    "B": {name: "Markdown"},
    "C": {name: "Spreadsheet"},
}