export interface modeInfoSingle{
    name: string;
    mode: string;
    editor: string;
}

export const modeInfo: Record<string, modeInfoSingle> = {
    "AB":{name:"APL",mode: "apl", editor: "codemirror"},
    "AC":{name:"PGP",mode: "asciiarmor", editor: "codemirror"},
    "AD":{name:"ASN.1",mode: "asn.1", editor: "codemirror"},
    "AE":{name:"Asterisk",mode: "asterisk", editor: "codemirror"},
    "AF":{name:"Brainfuck",mode: "brainfuck", editor: "codemirror"},
    "AG":{name:"C",mode: "clike", editor: "codemirror"},
    "AH":{name:"C++",mode: "clike", editor: "codemirror"},
    "AI":{name:"Cobol",mode: "cobol", editor: "codemirror"},
    "AJ":{name:"C#",mode: "clike", editor: "codemirror"},
    "AK":{name:"Clojure",mode: "clojure", editor: "codemirror"},
    "AL":{name:"ClojureScript",mode: "clojure", editor: "codemirror"},
    "AM":{name:"Closure Stylesheets (GSS)",mode: "css", editor: "codemirror"},
    "AN":{name:"CMake",mode: "cmake", editor: "codemirror"},
    "AO":{name:"CoffeeScript",mode: "coffeescript", editor: "codemirror"},
    "AP":{name:"Common Lisp",mode: "commonlisp", editor: "codemirror"},
    "AQ":{name:"Cypher",mode: "cypher", editor: "codemirror"},
    "AR":{name:"Cython",mode: "python", editor: "codemirror"},
    "AS":{name:"Crystal",mode: "crystal", editor: "codemirror"},
    "AT":{name:"CSS",mode: "css", editor: "codemirror"},
    "AU":{name:"CQL",mode: "sql", editor: "codemirror"},
    "AV":{name:"D",mode: "d", editor: "codemirror"},
    "AW":{name:"Dart",mode: "dart", editor: "codemirror"},
    "AX":{name:"diff",mode: "diff", editor: "codemirror"},
    "AY":{name:"Django",mode: "django", editor: "codemirror"},
    "AZ":{name:"Dockerfile",mode: "dockerfile", editor: "codemirror"},
    "Aa":{name:"DTD",mode: "dtd", editor: "codemirror"},
    "Ab":{name:"Dylan",mode: "dylan", editor: "codemirror"},
    "Ac":{name:"EBNF",mode: "ebnf", editor: "codemirror"},
    "Ad":{name:"ECL",mode: "ecl", editor: "codemirror"},
    "Ae":{name:"edn",mode: "clojure", editor: "codemirror"},
    "Af":{name:"Eiffel",mode: "eiffel", editor: "codemirror"},
    "Ag":{name:"Elm",mode: "elm", editor: "codemirror"},
    "Ah":{name:"Embedded JavaScript",mode: "htmlembedded", editor: "codemirror"},
    "Ai":{name:"Embedded Ruby",mode: "htmlembedded", editor: "codemirror"},
    "Aj":{name:"Erlang",mode: "erlang", editor: "codemirror"},
    "Ak":{name:"Esper",mode: "sql", editor: "codemirror"},
    "Al":{name:"Factor",mode: "factor", editor: "codemirror"},
    "Am":{name:"FCL",mode: "fcl", editor: "codemirror"},
    "An":{name:"Forth",mode: "forth", editor: "codemirror"},
    "Ao":{name:"Fortran",mode: "fortran", editor: "codemirror"},
    "Ap":{name:"F#",mode: "mllike", editor: "codemirror"},
    "Aq":{name:"Gas",mode: "gas", editor: "codemirror"},
    "Ar":{name:"Gherkin",mode: "gherkin", editor: "codemirror"},
    "As":{name:"GitHub Flavored Markdown",mode: "gfm", editor: "codemirror"},
    "At":{name:"Go",mode: "go", editor: "codemirror"},
    "Au":{name:"Groovy",mode: "groovy", editor: "codemirror"},
    "Av":{name:"HAML",mode: "haml", editor: "codemirror"},
    "Aw":{name:"Haskell",mode: "haskell", editor: "codemirror"},
    "Ax":{name:"Haskell (Literate)",mode: "haskell-literate", editor: "codemirror"},
    "Ay":{name:"Haxe",mode: "haxe", editor: "codemirror"},
    "Az":{name:"HXML",mode: "haxe", editor: "codemirror"},
    "A0":{name:"ASP.NET",mode: "htmlembedded", editor: "codemirror"},
    "A1":{name:"HTML",mode: "htmlmixed", editor: "codemirror"},
    "A2":{name:"HTTP",mode: "http", editor: "codemirror"},
    "A3":{name:"IDL",mode: "idl", editor: "codemirror"},
    "A4":{name:"Pug",mode: "pug", editor: "codemirror"},
    "A5":{name:"Java",mode: "clike", editor: "codemirror"},
    "A6":{name:"Java Server Pages",mode: "htmlembedded", editor: "codemirror"},
    "A7":{name:"JavaScript",mode: "javascript", editor: "codemirror"},
    "A8":{name:"JSON",mode: "javascript", editor: "codemirror"},
    "A9":{name:"JSON-LD",mode: "javascript", editor: "codemirror"},
    "A+":{name:"JSX",mode: "jsx", editor: "codemirror"},
    "A/":{name:"Jinja2",mode: "jinja2", editor: "codemirror"},
    "BA":{name:"Julia",mode: "julia", editor: "codemirror"},
    "BB":{name:"Kotlin",mode: "clike", editor: "codemirror"},
    "BC":{name:"LESS",mode: "css", editor: "codemirror"},
    "BD":{name:"LiveScript",mode: "livescript", editor: "codemirror"},
    "BE":{name:"Lua",mode: "lua", editor: "codemirror"},
    "BG":{name:"mIRC",mode: "mirc", editor: "codemirror"},
    "BH":{name:"MariaDB SQL",mode: "sql", editor: "codemirror"},
    "BI":{name:"Mathematica",mode: "mathematica", editor: "codemirror"},
    "BJ":{name:"Modelica",mode: "modelica", editor: "codemirror"},
    "BK":{name:"MUMPS",mode: "mumps", editor: "codemirror"},
    "BL":{name:"MS SQL",mode: "sql", editor: "codemirror"},
    "BM":{name:"mbox",mode: "mbox", editor: "codemirror"},
    "BN":{name:"MySQL",mode: "sql", editor: "codemirror"},
    "BO":{name:"Nginx",mode: "nginx", editor: "codemirror"},
    "BP":{name:"NSIS",mode: "nsis", editor: "codemirror"},
    "BQ":{name:"NTriples",mode: "ntriples", editor: "codemirror"},
    "BR":{name:"Objective-C",mode: "clike", editor: "codemirror"},
    "BS":{name:"Objective-C++",mode: "clike", editor: "codemirror"},
    "BT":{name:"OCaml",mode: "mllike", editor: "codemirror"},
    "BU":{name:"Octave",mode: "octave", editor: "codemirror"},
    "BV":{name:"Oz",mode: "oz", editor: "codemirror"},
    "BW":{name:"Pascal",mode: "pascal", editor: "codemirror"},
    "BX":{name:"PEG.js",mode: "pegjs", editor: "codemirror"},
    "BY":{name:"Perl",mode: "perl", editor: "codemirror"},
    "BZ":{name:"PHP",mode: "php", editor: "codemirror"},
    "Ba":{name:"Pig",mode: "pig", editor: "codemirror"},
    "Bb":{name:"Plain Text",mode: "null", editor: "codemirror"},
    "Bc":{name:"PLSQL",mode: "sql", editor: "codemirror"},
    "Bd":{name:"PostgreSQL",mode: "sql", editor: "codemirror"},
    "Be":{name:"PowerShell",mode: "powershell", editor: "codemirror"},
    "Bf":{name:"Properties files",mode: "properties", editor: "codemirror"},
    "Bg":{name:"ProtoBuf",mode: "protobuf", editor: "codemirror"},
    "Bh":{name:"Python",mode: "python", editor: "codemirror"},
    "Bi":{name:"Puppet",mode: "puppet", editor: "codemirror"},
    "Bj":{name:"Q",mode: "q", editor: "codemirror"},
    "Bk":{name:"R",mode: "r", editor: "codemirror"},
    "Bl":{name:"reStructuredText",mode: "rst", editor: "codemirror"},
    "Bm":{name:"RPM Changes",mode: "rpm", editor: "codemirror"},
    "Bn":{name:"RPM Spec",mode: "rpm", editor: "codemirror"},
    "Bo":{name:"Ruby",mode: "ruby", editor: "codemirror"},
    "Bp":{name:"Rust",mode: "rust", editor: "codemirror"},
    "Bq":{name:"SAS",mode: "sas", editor: "codemirror"},
    "Br":{name:"Sass",mode: "sass", editor: "codemirror"},
    "Bs":{name:"Scala",mode: "clike", editor: "codemirror"},
    "Bt":{name:"Scheme",mode: "scheme", editor: "codemirror"},
    "Bu":{name:"SCSS",mode: "css", editor: "codemirror"},
    "Bv":{name:"Shell",mode: "shell", editor: "codemirror"},
    "Bw":{name:"Sieve",mode: "sieve", editor: "codemirror"},
    "Bx":{name:"Slim",mode: "slim", editor: "codemirror"},
    "By":{name:"Smalltalk",mode: "smalltalk", editor: "codemirror"},
    "Bz":{name:"Smarty",mode: "smarty", editor: "codemirror"},
    "B0":{name:"Solr",mode: "solr", editor: "codemirror"},
    "B1":{name:"SML",mode: "mllike", editor: "codemirror"},
    "B2":{name:"Soy",mode: "soy", editor: "codemirror"},
    "B3":{name:"SPARQL",mode: "sparql", editor: "codemirror"},
    "B4":{name:"Spreadsheet",mode: "spreadsheet", editor: "codemirror"},
    "B5":{name:"SQL",mode: "sql", editor: "codemirror"},
    "B6":{name:"SQLite",mode: "sql", editor: "codemirror"},
    "B7":{name:"Squirrel",mode: "clike", editor: "codemirror"},
    "B8":{name:"Stylus",mode: "stylus", editor: "codemirror"},
    "B9":{name:"Swift",mode: "swift", editor: "codemirror"},
    "B+":{name:"sTeX",mode: "stex", editor: "codemirror"},
    "B/":{name:"LaTeX",mode: "stex", editor: "codemirror"},
    "CA":{name:"SystemVerilog",mode: "verilog", editor: "codemirror"},
    "CB":{name:"Tcl",mode: "tcl", editor: "codemirror"},
    "CC":{name:"Textile",mode: "textile", editor: "codemirror"},
    "CD":{name:"TiddlyWiki",mode: "tiddlywiki", editor: "codemirror"},
    "CE":{name:"Tiki wiki",mode: "tiki", editor: "codemirror"},
    "CF":{name:"TOML",mode: "toml", editor: "codemirror"},
    "CG":{name:"Tornado",mode: "tornado", editor: "codemirror"},
    "CH":{name:"troff",mode: "troff", editor: "codemirror"},
    "CI":{name:"TTCN",mode: "ttcn", editor: "codemirror"},
    "CJ":{name:"TTCN_CFG",mode: "ttcn-cfg", editor: "codemirror"},
    "CK":{name:"Turtle",mode: "turtle", editor: "codemirror"},
    "CL":{name:"TypeScript",mode: "javascript", editor: "codemirror"},
    "CM":{name:"TypeScript-JSX",mode: "jsx", editor: "codemirror"},
    "CN":{name:"Twig",mode: "twig", editor: "codemirror"},
    "CO":{name:"Web IDL",mode: "webidl", editor: "codemirror"},
    "CP":{name:"VB.NET",mode: "vb", editor: "codemirror"},
    "CQ":{name:"VBScript",mode: "vbscript", editor: "codemirror"},
    "CR":{name:"Velocity",mode: "velocity", editor: "codemirror"},
    "CS":{name:"Verilog",mode: "verilog", editor: "codemirror"},
    "CT":{name:"VHDL",mode: "vhdl", editor: "codemirror"},
    "CU":{name:"Vue.js Component",mode: "vue", editor: "codemirror"},
    "CV":{name:"XML",mode: "xml", editor: "codemirror"},
    "CW":{name:"XQuery",mode: "xquery", editor: "codemirror"},
    "CX":{name:"Yacas",mode: "yacas", editor: "codemirror"},
    "CY":{name:"YAML",mode: "yaml", editor: "codemirror"},
    "CZ":{name:"Z80",mode: "z80", editor: "codemirror"},
    "Ca":{name:"mscgen",mode: "mscgen", editor: "codemirror"},
    "Cb":{name:"xu",mode: "mscgen", editor: "codemirror"},
    "Cc":{name:"msgenny",mode: "mscgen", editor: "codemirror"},
    "Cd":{name:"WebAssembly",mode: "wast", editor: "codemirror"},
    "Ce":{name:"Markdown",mode: "markdown", editor: "tui"},
    "Cf":{name:"Spreadsheet",mode: "spreadsheet", editor: "spreadsheet"},
};
