name: Build site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: docs
    - name: setup
      run: npm install
    - name: build
      run: npm run publish
    - name: publish
      run: |
        cd docs
        git config --global user.email "26285364+choonkiatlee@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -m "update site"
        git push